// 组件样式预设定义
export interface WidgetStylePreset {
  id: string;
  name: string;
  description?: string;
  config: any;
}

// 每个组件的样式预设集合
export const widgetStylePresets: Record<string, WidgetStylePreset[]> = {
  player: [
    {
      id: 'default',
      name: '图标+文字',
      description: '显示玩家名称和队伍信息',
      config: {
        style: {
          minWidth: 200,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: false,
        showText: true,
        title: { order: 3, color: 'white' },
        text: { size: 'sm', color: 'dimmed' },
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示文字，无背景卡片',
      config: {
        style: {
          minWidth: 150,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showIcon: false,
        showText: true,
        title: { order: 4, color: 'white' },
        text: { size: 'sm', color: 'white' },
      },
    },
    {
      id: 'icon-text',
      name: '图标+文字',
      description: '显示图标和文字（如果有图标）',
      config: {
        style: {
          minWidth: 220,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: true,
        title: { order: 3, color: 'white' },
        text: { size: 'sm', color: 'dimmed' },
      },
    },
    {
      id: 'bold-text',
      name: '粗体文字',
      description: '大号粗体文字显示',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
        },
        showIcon: false,
        showText: true,
        title: { order: 1, color: '#ffffff' },
        text: { size: 'lg', color: '#cccccc' },
      },
    },
  ],
  health: [
    {
      id: 'default',
      name: '图标+文字+进度条',
      description: '显示图标、文字和进度条',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: true,
        showProgress: true,
        progress: { color: 'red', size: 'lg', radius: 'xl' },
        icon: { color: 'red', size: 'sm' },
        text: { size: 'xs', color: 'red.2' },
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示文字，无图标和进度条',
      config: {
        style: {
          minWidth: 120,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showIcon: false,
        showText: true,
        showProgress: false,
        text: { size: 'md', color: 'red', fw: 700 },
      },
    },
    {
      id: 'icon-only',
      name: '极简图标',
      description: '只显示图标，无文字和进度条',
      config: {
        style: {
          minWidth: 60,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: false,
        showProgress: false,
        icon: { color: 'red', size: 'lg' },
      },
    },
    {
      id: 'progress-only',
      name: '极简进度条',
      description: '只显示进度条，无图标和文字',
      config: {
        style: {
          minWidth: 200,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: false,
        showText: false,
        showProgress: true,
        progress: { color: 'red', size: 'xl', radius: 'xl' },
      },
    },
  ],
  armor: [
    {
      id: 'default',
      name: '图标+文字+进度条',
      description: '显示图标、文字和进度条',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: true,
        showProgress: true,
        armorProgress: { color: 'blue', size: 'sm', radius: 'xl' },
        icon: { color: 'blue', size: 'sm' },
        moneyText: { size: 'xs', color: 'yellow.3' },
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示文字，无图标和进度条',
      config: {
        style: {
          minWidth: 150,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showIcon: false,
        showText: true,
        showProgress: false,
        moneyText: { size: 'md', color: 'yellow', fw: 700 },
      },
    },
    {
      id: 'icon-only',
      name: '极简图标',
      description: '只显示图标，无文字和进度条',
      config: {
        style: {
          minWidth: 60,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: false,
        showProgress: false,
        icon: { color: 'blue', size: 'lg' },
      },
    },
    {
      id: 'progress-only',
      name: '极简进度条',
      description: '只显示进度条，无图标和文字',
      config: {
        style: {
          minWidth: 200,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: false,
        showText: false,
        showProgress: true,
        armorProgress: { color: 'blue', size: 'xl', radius: 'xl' },
      },
    },
  ],
  score: [
    {
      id: 'default',
      name: '完整显示',
      description: '显示地图名称和比分',
      config: {
        style: {
          minWidth: 180,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showMapName: true,
        showScore: true,
        tColor: 'yellow',
        ctColor: 'cyan',
        textSize: 'sm',
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示比分文字，无背景',
      config: {
        style: {
          minWidth: 120,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showMapName: false,
        showScore: true,
        tColor: 'yellow',
        ctColor: 'cyan',
        textSize: 'lg',
      },
    },
    {
      id: 'score-only',
      name: '只显示比分',
      description: '只显示比分，不显示地图名称',
      config: {
        style: {
          minWidth: 150,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showMapName: false,
        showScore: true,
        tColor: 'yellow',
        ctColor: 'cyan',
        textSize: 'md',
      },
    },
    {
      id: 'large-bold',
      name: '超大粗体',
      description: '超大号比分，粗体显示',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(0, 0, 0, 0.9)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
        },
        showMapName: true,
        showScore: true,
        tColor: 'yellow',
        ctColor: 'cyan',
        textSize: 'xl',
      },
    },
  ],
  agentstream: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，白色文字',
      config: {
        style: {
          minWidth: 400,
          maxWidth: 800,
          background: 'rgba(20, 20, 25, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.1)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        text: { size: 'md', color: 'white' },
        liveTimeout: 10000,
      },
    },
    {
      id: 'neon-cyan',
      name: '霓虹青色',
      description: '黑色背景，青色文字和边框',
      config: {
        style: {
          minWidth: 450,
          maxWidth: 900,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(0, 255, 255, 0.8)',
          backdropFilter: 'none',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(0, 255, 255, 0.8)',
        },
        text: { size: 'lg', color: '#00ffff' },
        liveTimeout: 10000,
      },
    },
    {
      id: 'glass-transparent',
      name: '透明玻璃',
      description: '完全透明，强模糊效果',
      config: {
        style: {
          minWidth: 350,
          maxWidth: 700,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.2)',
          backdropFilter: 'blur(25px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'md',
        },
        text: { size: 'sm', color: 'rgba(255, 255, 255, 0.9)' },
        liveTimeout: 10000,
      },
    },
    {
      id: 'bold-black',
      name: '粗体黑色',
      description: '纯黑背景，大号粗体',
      config: {
        style: {
          minWidth: 500,
          maxWidth: 1000,
          background: 'rgba(0, 0, 0, 0.98)',
          borderColor: 'rgba(255, 255, 255, 0.4)',
          backdropFilter: 'blur(5px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.4)',
        },
        text: { size: 'xl', color: '#ffffff' },
        liveTimeout: 10000,
      },
    },
  ],
  emoji: [
    {
      id: 'default',
      name: '标准大小',
      description: '200x200 标准尺寸',
      config: {
        style: { width: 200, height: 200, minWidth: 200, minHeight: 200 },
        size: 200,
        liveTimeout: 10000,
      },
    },
    {
      id: 'large',
      name: '超大尺寸',
      description: '400x400 超大表情包',
      config: {
        style: { width: 400, height: 400, minWidth: 400, minHeight: 400 },
        size: 400,
        liveTimeout: 10000,
      },
    },
    {
      id: 'small',
      name: '迷你尺寸',
      description: '100x100 迷你表情包',
      config: {
        style: { width: 100, height: 100, minWidth: 100, minHeight: 100 },
        size: 100,
        liveTimeout: 10000,
      },
    },
    {
      id: 'medium',
      name: '中等尺寸',
      description: '300x300 中等大小',
      config: {
        style: { width: 300, height: 300, minWidth: 300, minHeight: 300 },
        size: 300,
        liveTimeout: 10000,
      },
    },
  ],
  tts: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准大小',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(15, 15, 20, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        size: 'md',
        showProgress: true,
      },
    },
    {
      id: 'neon-purple',
      name: '霓虹紫色',
      description: '紫色边框，黑色背景',
      config: {
        style: {
          minWidth: 350,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 0, 255, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(255, 0, 255, 0.8)',
        },
        size: 'lg',
        showProgress: true,
      },
    },
    {
      id: 'minimal-thin',
      name: '极简细条',
      description: '透明背景，细边框',
      config: {
        style: {
          minWidth: 250,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'xs',
          borderRadius: 'lg',
          shadow: 'none',
        },
        size: 'sm',
        showProgress: true,
      },
    },
    {
      id: 'bold-large',
      name: '粗大醒目',
      description: '超大尺寸，粗边框',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(0, 0, 0, 0.98)',
          borderColor: 'rgba(255, 255, 255, 0.5)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.5)',
        },
        size: 'lg',
        showProgress: true,
      },
    },
  ],
  bomb: [
    {
      id: 'default',
      name: '图标+文字+进度',
      description: '显示图标、文字和进度环',
      config: {
        style: {
          minWidth: 320,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: true,
        showProgress: true,
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示文字，无图标和进度',
      config: {
        style: {
          minWidth: 200,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showIcon: false,
        showText: true,
        showProgress: false,
      },
    },
    {
      id: 'icon-only',
      name: '极简图标',
      description: '只显示图标，无文字和进度',
      config: {
        style: {
          minWidth: 60,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: false,
        showProgress: false,
      },
    },
    {
      id: 'progress-only',
      name: '极简进度',
      description: '只显示进度环，无图标和文字',
      config: {
        style: {
          minWidth: 100,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: false,
        showText: false,
        showProgress: true,
      },
    },
    {
      id: 'minimal-thin',
      name: '极简细条',
      description: '透明背景，细边框',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-large',
      name: '粗大醒目',
      description: '超大尺寸，粗边框',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(20, 0, 0, 0.9)',
          borderColor: 'rgba(255, 50, 50, 0.6)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'lg',
          shadow: 'xl',
          border: '3px solid rgba(255, 50, 50, 0.6)',
        },
      },
    },
  ],
  weapons: [
    {
      id: 'default',
      name: '图标+文字',
      description: '显示武器图标和名称',
      config: {
        style: {
          minWidth: 240,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: true,
      },
    },
    {
      id: 'text-only',
      name: '极简文字',
      description: '只显示文字，无图标',
      config: {
        style: {
          minWidth: 150,
          background: 'transparent',
          borderColor: 'transparent',
          backdropFilter: 'none',
          padding: 'xs',
          borderRadius: 'none',
          shadow: 'none',
        },
        showIcon: false,
        showText: true,
      },
    },
    {
      id: 'icon-only',
      name: '极简图标',
      description: '只显示图标，无文字',
      config: {
        style: {
          minWidth: 200,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'sm',
          borderRadius: 'md',
          shadow: 'xl',
        },
        showIcon: true,
        showText: false,
      },
    },
    {
      id: 'compact',
      name: '紧凑显示',
      description: '紧凑布局，图标和文字都显示',
      config: {
        style: {
          minWidth: 180,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'xs',
          borderRadius: 'sm',
          shadow: 'md',
        },
        showIcon: true,
        showText: true,
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 200,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-compact',
      name: '粗体紧凑',
      description: '紧凑布局，粗边框',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'md',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
  stats: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准统计',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-green',
      name: '霓虹绿色',
      description: '绿色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 320,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(0, 255, 0, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(0, 255, 0, 0.8)',
        },
      },
    },
    {
      id: 'minimal-transparent',
      name: '极简透明',
      description: '透明背景，细边框',
      config: {
        style: {
          minWidth: 240,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-grid',
      name: '粗体网格',
      description: '网格布局，粗边框',
      config: {
        style: {
          minWidth: 360,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
  round: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准回合统计',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-yellow',
      name: '霓虹黄色',
      description: '黄色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 320,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 0, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(255, 255, 0, 0.8)',
        },
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 240,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-large',
      name: '粗大醒目',
      description: '超大尺寸，粗边框',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.4)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.4)',
        },
      },
    },
  ],
  faceit: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准Faceit统计',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-purple',
      name: '霓虹紫色',
      description: '紫色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 350,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 0, 255, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(255, 0, 255, 0.8)',
        },
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-wide',
      name: '粗体宽屏',
      description: '宽屏布局，粗边框',
      config: {
        style: {
          minWidth: 500,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
  matchteams: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准队伍显示',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-cyan',
      name: '霓虹青色',
      description: '青色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 500,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(0, 255, 255, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(0, 255, 255, 0.8)',
        },
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 350,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-wide',
      name: '粗体宽屏',
      description: '宽屏布局，粗边框',
      config: {
        style: {
          minWidth: 600,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
  myteam: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准队伍显示',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-blue',
      name: '霓虹蓝色',
      description: '蓝色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 350,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(0, 150, 255, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(0, 150, 255, 0.8)',
        },
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-compact',
      name: '粗体紧凑',
      description: '紧凑布局，粗边框',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
  enemyteam: [
    {
      id: 'default',
      name: '经典深色',
      description: '深色背景，标准队伍显示',
      config: {
        style: {
          minWidth: 300,
          background: 'rgba(15, 15, 20, 0.74)',
          borderColor: 'rgba(255, 255, 255, 0.12)',
          backdropFilter: 'blur(12px)',
          padding: 'md',
          borderRadius: 'md',
          shadow: 'xl',
        },
      },
    },
    {
      id: 'neon-red',
      name: '霓虹红色',
      description: '红色发光边框，黑色背景',
      config: {
        style: {
          minWidth: 350,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 0, 0, 0.8)',
          backdropFilter: 'none',
          padding: 'lg',
          borderRadius: 'md',
          shadow: 'xl',
          border: '2px solid rgba(255, 0, 0, 0.8)',
        },
      },
    },
    {
      id: 'minimal-glass',
      name: '极简玻璃',
      description: '透明玻璃效果，细边框',
      config: {
        style: {
          minWidth: 280,
          background: 'rgba(255, 255, 255, 0.05)',
          borderColor: 'rgba(255, 255, 255, 0.15)',
          backdropFilter: 'blur(20px)',
          padding: 'sm',
          borderRadius: 'lg',
          shadow: 'none',
        },
      },
    },
    {
      id: 'bold-compact',
      name: '粗体紧凑',
      description: '紧凑布局，粗边框',
      config: {
        style: {
          minWidth: 400,
          background: 'rgba(0, 0, 0, 0.95)',
          borderColor: 'rgba(255, 255, 255, 0.3)',
          backdropFilter: 'blur(8px)',
          padding: 'xl',
          borderRadius: 'sm',
          shadow: 'xl',
          border: '3px solid rgba(255, 255, 255, 0.3)',
        },
      },
    },
  ],
};

// 获取组件的样式预设列表
export function getWidgetStylePresets(widgetName: string): WidgetStylePreset[] {
  return widgetStylePresets[widgetName] || [
    {
      id: 'default',
      name: '默认样式',
      config: {},
    },
  ];
}

// 获取指定的样式预设
export function getWidgetStylePreset(widgetName: string, presetId: string): WidgetStylePreset | null {
  const presets = getWidgetStylePresets(widgetName);
  return presets.find((p) => p.id === presetId) || presets[0] || null;
}
